spring:
  application:
    name: gateway

security:
  basic:
    enabled: false

endpoints:
  routes:
    sensitive: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  readTimeout: 20000
  connectTimeout: 20000
  eureka:
    enabled: true


eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  prefix: /api
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    project-service:
      path: /projects/**
      # url: http://localhost:4000
      serviceId: project-service
      sensitiveHeaders:
    employee-service:
      path: /employees/**
      # url: http://localhost:4000
      serviceId: employee-service
      sensitiveHeaders:
server:
  port: 8080