spring:
  application:
    name: employee-service
  data:
    mongodb:
      host: localhost
      database: employees
      port: 27017

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

ribbon:
  eureka:
    enabled: true

server:
  port: 5000